PUT http://localhost:3001/user/update/completedRoutes
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsImlkIjoiNjUwMDIyYjM2ZTdjMGY2MDkwYzM2N2Q1IiwiaWF0IjoxNzEyNTI5NjQzfQ.8-XSV8vYp-CwcKP8CkpIYjgCgIALWnMaYyQYbHn59Mk

{
    "crag": "64788993b628b906c671299c",
  "sector": "64788993b628b906c671299a",
  "route": "6478898db628b906c671297a",
  "completionType": "onSight"}
